from ipamd import App
from ipamd.public.models.md import Environment
app = App(name="ELP-R")
app.use('Calvados1')
app.builder.af2('polyf', 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF')
app.builder.af2('polyfe', 'EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE')
mol = app.builder.protein_from_pdb('polyf.pdb')
mol1 = app.builder.protein_from_pdb('polyfe.pdb')
box = app.builder.new_simulation_box(20, 20, 20)
env = Environment('pure water')
env.set_temperature(273)
box.in_solvent(env)
box.place_molecule_randomly(mol, 40, max_tries=20)
box.place_molecule_randomly(mol1, 10, max_tries=20)
simulation = app.simulation.new_simulation(box, 'ELP-R', total_time='20ns', snap_shot=10)
simulation.run()
box.frame(10)
box.merge_nearest()
box.align_center()
box.to_xml('polyf-r')