class PdbReader:
    def __init__(self, path):
        self.pdb_file = open(path, 'r')

    def read(self):
        atom_info_list = []
        connect_info_list = []
        for line in self.pdb_file:
            line = line[:-1]
            if line.startswith('ATOM') or line.startswith('HETATM'):
                type_ = line[0:6].strip()
                atom_no = line[6:11].strip()
                atom_name = line[12:16].strip()
                res_name = line[17:20].strip()
                chain_id = line[21]
                residue_id = line[22:26].strip()
                coord_x = line[30:38].strip()
                coord_y = line[38:46].strip()
                coord_z = line[46:54].strip()
                temp_factor = line[60:66].strip()
                element = line[76:78].strip()
                charge = line[78:80].strip()

                atom_info_list.append({
                    "type": type_,
                    "atom_no": int(atom_no),
                    "atom_name": atom_name,
                    "residue_name": res_name,
                    "chain_id": chain_id,
                    "residue_id": int(residue_id),
                    "coord_x": float(coord_x) / 10,
                    "coord_y": float(coord_y) / 10,
                    "coord_z": float(coord_z) / 10,
                    "temp_factor": float(temp_factor),
                    "element": element,
                    "charge": 0 if charge == '' else int(charge)
                })
        return atom_info_list, connect_info_list

class PdbWriter:
    def __init__(self, path, title='PDB file'):
        self.pdb_file = open(path, 'w')
        self.last_atom_info = None
        info = f"""HEADER
TITLE    {title}                                            
REMARK   generated by IPAMD
REMARK
"""
        self.pdb_file.write(info)

    def write_line(self, atom_info):
        self.last_atom_info = atom_info
        line = f'{atom_info["type"]:<6}{atom_info["atom_no"]:>5} {atom_info["atom_name"]:<4} '
        line += f'{atom_info["residue_name"]:>3} {atom_info["chain_id"]}{atom_info['residue_id']:>4}    '
        line += f'{atom_info["coord_x"] * 10:8.3f}{atom_info["coord_y"] * 10:8.3f}{atom_info["coord_z"] * 10:8.3f}'
        line += f'{1.0:6.2f}{atom_info["temp_factor"]:6.2f}          {atom_info["element"]:>2}'
        line += f'{''if atom_info["charge"] == 0 else atom_info["charge"]:>2}\n'
        self.pdb_file.write(line)

    def write_lines(self, atom_infos):
        for atom_info in atom_infos:
            self.write_line(atom_info)
        self.write_ter()

    def write_ter(self):
        line = f'TER   {self.last_atom_info["atom_no"]:>5}      '
        line += f'{self.last_atom_info["residue_name"]:>3}{self.last_atom_info["chain_id"]}'
        line += f'{self.last_atom_info['residue_id']:>4} \n'
        self.pdb_file.write(line)

    def write_connect(self, connect_info):
        pass

    def end(self):
        self.pdb_file.write('END\n')